### ISSUE TITLE
про интересную вакансию

### ISSUE THREAD

**Issue by tatiana-litvak** [lisyarus/parse#1]
Илья , здравствуйте! 
Вижу, что Вы давно и успешно работали на С++ и очень надеюсь, что не бросили это занятие ))
Хочу предложить Вам рассмотреть вакансию - я ищу С++ разработчика с опытом многопоточного и сетевого программирования и хорошим знанием алгоритмов, а Вы на него очень похожи)). Есть возможность поработать над большим почтовым сервисом в крупном медиахолдинге. 
Давайте созвонимся, обсудим подробности?
С уважением, Татьяна

**Comment by lisyarus** [comment]
Здравствуйте, Виктория!
Большое спасибо за предложение, но оно мне категорически не интересно. К тому же, не используйте, пожалуйста, issues не по назначению: они служат для обсуждения конкретных вещей в конкретных проектах, а просто связаться с человеком можно огромным количеством других, более подходящих способов.
С уважением, Никита.
